name: github action to print rails version

on:
  push:
    branches:
      - main
jobs:
  ready:
    name: ready the job to run
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Print Author Name
        run: |
          echo ${{github.actor}}
          echo ${{github.event.pusher.name}}
      - name: find environment
        id: find_env
        run: |
          echo "::set-output name=environment::production"
  build:
    name: run job for github.ref_name
    runs-on: [ubuntu-latest]

    steps:
      - name: Print Author name
        run: |
          echo ${{github.actor}}
          echo ${{github.event.pusher.name}}
      - name: find environment
        id: find_env
        run: |
          if [ ${{ github.ref_name }} == "production" ]; then
            echo "::set-output name=environment::production"
          else
            echo "::set-output name=environment::staging"
          fi

      - name: "print bloddy everything of ${{ steps.find_env.outputs.environment }}"
        run: |
          echo ${{github}}
          echo ${{github.ref}}
          echo ${{github.ref_name}}
      - name: "Print bloddy everything of ${{ steps.find_env.outputs.environment }}"
        run: |
          if [ ${{ github.ref_name }} == "staging" ]; then
            echo ${{github}}
            echo ${{github.ref}}
            echo ${{github.ref_name}}
          else
            echo My Name is Sabin Nepal
          fi
      - name: "print environment of ${{ steps.find_env.outputs.environment }}"
        run: |
          echo ${{ steps.find_env.outputs.environment }}

      - name: Send Honeybadger Notification
        uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: hbp_9JchL0CTSoHaevIQn95TBWAwxS48OD0kj0mu
          environment: ${{ steps.find_env.outputs.environment }}

     
#      - uses: actions/checkout@v2
#      - uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.1.0
#          bundler-cache: true
#        id: setup_ruby
#      - name: print ruby-setup output
#        run: |
#          echo ${{join(steps.setup_ruby.outputs.*, '\n')}}
#          echo ${{join(steps.setup_ruby.outputs.ruby-prefix, '\n')}}
#          
#      - name: print all the environment variables from ci
#        run: echo ${GITHUB_REF##*/}
#  deploy:
#    name: deploy code
#    runs-on: [ubuntu-latest, github.ref_name ]
#    steps:
#    - run: |
#        echo ${{join(jobs.build.steps.setup_ruby.outputs.ruby-prefix, '\n')}}
