name: github action to print rails version

on:
  push:
    branches:
      - main
jobs: 
  docker:
    name: "run job for ${{github.ref}}##*/"
    runs-on: [self-hosted , "${{github.ref}}" ]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
        id: setup_ruby
      - name: print ruby-setup output
        run: |
          echo ${{join(steps.setup_ruby.outputs.*, '\n')}}
          echo ${{join(steps.setup_ruby.outputs.ruby-prefix, '\n')}}
          
      - name: print all the environment variables from ci
        run: echo ${GITHUB_REF##*/}
